# image will be published to ghcr.io/<user>/<name>
name: LegionLand

description: Bazzite gnome deck with hyprland and SDDM switching (does not work)

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: 40 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - cliphist
      - dwarfs
      - fish
      - gnome-shell
      - gnome-settings-daemon 
      - gnome-control-center 
      - nautilus 
      - gnome-terminal 
      - gnome-software 
      - gnome-screenshot 
      - gnome-system-monitor
      - hyprdim
      - hypridle
      - hyprland
      - hyprland-plugins
      - hyprlock
      - hyprnome
      - hyprpaper
      - hyprpicker
      - hyprshot
      - kde-material-you-colors
      - kitty
      - lxappearance
      - micro
      - nwg-clipman
      - nwg-bar
      - nwg-displays
      - nwg-dock
      - nwg-drawer
      - nwg-icon-picker
      - nwg-look
      - nwg-menu
      - nwg-panel
      - nwg-shell
      - nwg-shell-config
      - nwg-shell-wallpapers
      - openssh
      - openssh-server
      - python-pywal
      - python-materialyoucolor
      - pyprland
      - qt6-qtvirtualkeyboard
      - ranger
      - rofi-wayland
      - sddm-kcm
      - sddm-themes
      - starship
      - swaylock-effects
      - swaync
      - swww
      - Thunar
      - thunar-volman
      - thunar-archive-plugin
      - thunar-vcs-plugin
      - thunar-media-tags-plugin 
      - tailscale
      - unclutter-xfixes
      - waybar-git
      - waypaper
      - wlogout
      - xdg-desktop-portal-hyprland
    remove:
      #-

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.libreoffice.LibreOffice
    user:
      install: 
         - com.vscodium.codium
         - org.libreoffice.LibreOffice
         
  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        #-
    user:
      enabled:
        #- 
      disabled:
        #-

  - type: fonts
    fonts:
     nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix.
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
     google-fonts:
      - Roboto
      - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      - sddm/enable-sddm.sh

