# image will be published to ghcr.io/<user>/<name>
name: LegionLand

description: Bazzite gnome deck with hyprland and SDDM switching (does not work)

base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: 40 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
    - aquamarine
    - aylurs-gtk-shell
    - bluez
    - brightnessctl
    - cliphist
    - niri
    - dwarfs
    - eww-wayland-git
    - fish
    - gnome-control-center
    - gnome-screenshot
    - gnome-settings-daemon
    - gnome-shell
    - gnome-software
    - gnome-system-monitor
    - gnome-terminal
    - hyprcursor
    - hyprdim
    - hypridle
    - hyprland
    - hyprland-contrib
    - hyprland-plugins
    - hyprland-welcome
    - hyprlang
    - hyprlock
    - hyprnome
    - hyprpaper
    - hyprpicker
    - hyprshot
    - hyprutils
    - kde-material-you-colors
    - kitty
    - lxappearance
    - micro
    - mpvpaper
    - nautilus
    - nwg-bar
    - nwg-clipman
    - nwg-displays
    - nwg-dock
    - nwg-drawer
    - nwg-icon-picker
    - nwg-look
    - nwg-menu
    - nwg-panel
    - nwg-shell
    - nwg-shell-config
    - nwg-shell-wallpapers
    - openssh
    - openssh-server
    - plasma-breeze
    - plasma-desktop
    - plasma-workspace
    - pyprland
    - python-materialyoucolor
    - python-pywal
    - qt6-qtdeclarative
    - qt6-qtsvg
    - qt5-qtvirtualkeyboard
    #- qt6-qtvirtualkeyboard
    - ranger
    - rofi-wayland
    - scenefx
    - swayfx
    - sddm
    - sddm-breeze
    - sddm-kcm
    - sddm-themes
    - starship
    - swappy
    - swaylock-effects
    # - swaync
    - swww
    - tailscale
    - Thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
    - thunar-vcs-plugin
    - thunar-volman
    - tomlplusplus
    - unclutter-xfixes
    - waybar-git
    - waypaper
    - wayvnc
    - wl-clipboard
    - wlogout
    - xcur2png
    - xdg-desktop-portal-hyprland
    - zsh
    - dolphin 
    - konsole 
    - plasma-systemsettings 
    - kscreen
    - kde-settings 
    - kde-style-breeze 
    - breeze-gtk 
    - kde-gtk-config
    - plasma-nm
    - plasma-pa
    - kwrite 
    - gwenview 
    - okular 
    - ark 
    - kate 
    - kcalc
    - fcitx5
    - fcitx5-autostart
    - fcitx5-data
    - fcitx5-devel
    - fcitx5-libs
    - qt5-qtvirtualkeyboard-examples
    #- qt5-qtvirtualkeyboard-devel
    - libva
    - libvdpau
    - libxcb
    - traceroute
    - ocl-icd
    - pcre2
    - libxi
    - xcb-util-wm
    - xcb-util-image
    - xcb-util-renderutil
    - xcb-util-keysyms
    - fontconfig
    - alsa-lib
    - alsa-plugins
    - alsa-plugins-pulseaudio
    remove:
      #-

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.libreoffice.LibreOffice
    user:
      install: 
         - com.vscodium.codium
         - org.libreoffice.LibreOffice
         
  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        #-
    user:
      enabled:
        #- 
      disabled:
        #-

  - type: fonts
    fonts:
     nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix.
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
     google-fonts:
      - Roboto
      - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      - sddm/enable-sddm.sh

