# image will be published to ghcr.io/<user>/<name>
name: LegionLand

description: Bazzite gnome deck with hyprland and SDDM switching (does not work)

base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: 40 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jc141/DwarFS/repo/fedora-%OS_VERSION%/jc141-DwarFS-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/wlogout/repo/fedora-%OS_VERSION%/wef-wlogout-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - cliphist
      - dwarfs
      - fish
      - hyprdim
      - hypridle
      - hyprland
      - hyprland-plugins
      - hyprlock
      - hyprnome
      - hyprpaper
      - hyprpicker
      - hyprshot
      - kitty
      - lxappearance
      - micro
      - nwg-clipman
      - plasma-breeze
      - plasma-desktop
      - plasma-workspace
      - pyprland
      - qt5-qtvirtualkeyboard 
      - rofi-wayland
      - sddm
      - sddm-breeze
      - starship
      - swaylock-effects
      - swaync
      - swww
      - tailscale
      - unclutter-xfixes
      - waybar-git
      - waypaper
      - wlogout
      - xdg-desktop-portal-hyprland
      - dolphin 
      - konsole 
      - systemsettings 
      - kscreen
      - kde-settings 
      - kde-style-breeze 
      - breeze-gtk 
      - kde-gtk-config
      - plasma-nm
      - plasma-pa
      - kwrite 
      - gwenview 
      - okular 
      - ark 
      - kate 
      - kcalc
    remove:
      #-

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.libreoffice.LibreOffice
    user:
      install: 
         - com.vscodium.codium
         - io.github.zen_browser.zen
         - org.libreoffice.LibreOffice
         
  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        #-
    user:
      enabled:
        #- 
      disabled:
        #-

  - type: fonts
    fonts:
     nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix.
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
     google-fonts:
      - Roboto
      - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      - sddm/enable-sddm.sh

