# image will be published to ghcr.io/<user>/<name>
name: LegionLand

description: Bazzite gnome deck with hyprland and SDDM switching (does not work)

base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: 40 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mochaa/swaync/repo/fedora-%OS_VERSION%/mochaa-swaync-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - kitty
      - rofi-wayland 
      - starship
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprland-plugins
      - hyprpaper
      - hyprpicker
      - hypridle
      - hyprlock
      - hyprshot
      - waybar-git
      - cliphist
      - nwg-clipman
      - swww
      - waypaper
      - hyprnome
      - hyprdim
      - swaylock-effects
      - pyprland
      - swaync
      - sddm
      - tailscale
      - fish
      - qemu
      - virt-manager
      - edk2-ovmf
      - btrfs-assistant
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
     repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
     repo-name: flathub
      install:
        - org.libreoffice.LibreOffice
    user:
      install: 
        - io.github.zen_browser.zen
        - com.vscodium.codium
        - org.libreoffice.LibreOffice

  - type: systemd
    system:
      enabled:
        - tailscaled

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      # Custom changes for deckstation
      - sddm/enable-sddm.sh
      - main/add-justfile.sh
      - main/deckstation-setup.sh
      - fixes/btrfs-assistant.sh
